name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - name: Cache pip dependencies
        uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install pip dependencies
        run: pip install -U -r requirements.txt
      - name: Cache font
        uses: actions/cache@v2
        id: cache-font
        with:
          path: .font
          key: ${{ runner.os }}-font
      - name: Download font
        if: steps.cache-font.outputs.cache-hit != 'true'
        run: |
          mkdir .font
          iwr https://mirrors.cloud.tencent.com/adobe-fonts/source-han-serif/OTF/SimplifiedChinese/SourceHanSerifSC-Medium.otf -OutFile .font/SourceHanSerifSC-Medium.otf
      - name: Generate font subset
        run: |
          mkdir font
          python tool/generate-font-subset.py lib/**/*.py .font/SourceHanSerifSC-Medium.otf font/SourceHanSerifSC-Medium-Subset.otf
      - name: Setup UPX
        run: choco install upx --no-progress
      - name: Set vars
        id: vars
        run: |
          echo "::set-output name=commitShort::$(git rev-parse --short HEAD)"
          echo "::set-output name=buildTime::$(Get-Date -Format 'yyyyMMdd-HHmmss')"
      - name: Build executable
        run: |
          ./build-windows.ps1
          mv dist/striker.exe dist/striker-${{ steps.vars.outputs.buildTime }}-${{ steps.vars.outputs.commitShort }}.exe
          Get-FileHash dist/striker-${{ steps.vars.outputs.buildTime }}-${{ steps.vars.outputs.commitShort }}.exe -Algorithm SHA256
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: striker
          path: dist/striker-${{ steps.vars.outputs.buildTime }}-${{ steps.vars.outputs.commitShort }}.exe
